pub(crate) mod automation;
pub(crate) mod insights;
#[cfg(feature = "desktop")]
pub(crate) mod p2p_bridge;
pub(crate) mod dxt;
pub(crate) mod event_sink;
pub(crate) mod filesystem;
pub(crate) mod git;
pub(crate) mod mcp;
pub(crate) mod skills;
pub(crate) mod skillssh;
pub(crate) mod sleep;
