name: CI macOS frontend

on:
  workflow_dispatch:

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: install frontend dependencies
        run: bun install

      - name: Build Tauri App
        run: bun run build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
